# Generated by Django 4.2.1 on 2023-05-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basededatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name': 'Orden', 'verbose_name_plural': 'Ordenes'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id_stock',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
