# Generated by Django 4.2.1 on 2023-06-04 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modified_date', models.DateField(verbose_name='fecha modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha eliminacion')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('modified_date', models.DateField(verbose_name='fecha modificacion')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='fecha eliminacion')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stock', models.IntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoria de producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        )
    ]
