# Generated by Django 4.2.1 on 2023-06-05 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_historicalproduct_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',), 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='state',
            new_name='status',
        ),
        
        migrations.RenameField(
            model_name='product',
            old_name='state',
            new_name='status',
        ),
    ]
