# Generated by Django 4.2.1 on 2023-06-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_rename_state_category_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='historicalproduct',
            old_name='status',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='state',
        ),
    ]
