# Generated by Django 4.2.1 on 2023-06-06 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_status_category_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificacion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificacion'),
        ),
    ]
