# Generated by Django 4.2.1 on 2023-06-12 19:41
from django.db import migrations
from django.db import migrations, models
import django.db.models.deletion

def set_default_order(apps, schema_editor):
    Invoice = apps.get_model('invoice', 'Invoice')
    Invoice.objects.filter(order__isnull=True).update(order=1)


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='cart',
        ),
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
