# Generated by Django 4.2.1 on 2023-06-13 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
    ]
