# Generated by Django 4.2.1 on 2023-06-13 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_alter_invoice_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Modelo Base', 'verbose_name_plural': 'Modelos Base'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='fecha eliminacion'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificacion'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='state',
            field=models.BooleanField(default=True, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='created_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='deleted_date',
            field=models.DateField(auto_now=True, verbose_name='fecha eliminacion'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='fecha modificacion'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='state',
            field=models.BooleanField(default=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
