# Generated by Django 4.2.1 on 2023-06-13 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_options_alter_invoiceitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'verbose_name': 'Factura', 'verbose_name_plural': 'Facturas'},
        ),
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'Item Factura', 'verbose_name_plural': 'Items Facturas'},
        ),
    ]
